### ISSUE TITLE
Please remove your custom aardwolf_colors.lua file.

### ISSUE THREAD

**Issue by fiendish** [Shindo-Aardwolf/Mushclient-Consider#3]
Replacing one of my files with something from 2 years ago is guaranteed to cause problems. Please do not distribute your own copy. If you need me to update something, I will.

Alternately it needs to be clear and streamlined for people who don't understand the technical consequences of replacing existing files that everything in this repo needs to be kept walled off in its own subfolder.

**Comment by Shindo-Aardwolf** [comment]
thanks for the feed back. I'll get that sorted out. I can't remember why I was including it

**Comment by Shindo-Aardwolf** [comment]
file removed as per request from Fiendish
